[theme]
base="dark"

primaryColor="#a8dadc"  # Blue primary color
secondaryBackgroundColor="#1d3557"  # blue background for sidebar
backgroundColor="#212946" #"#457b9d"  # Lightblue color
textColor="#f1faee"  # Light greyblue text color